### ISSUE TITLE
Training code

### ISSUE THREAD

**Issue by abduallahmohamed** [JoeHEZHAO/expert_traj#2]
Thanks for your work! 
I was wondering if you are able to release the training code?

**Comment by JoeHEZHAO** [comment]
Hi Abdullaha, 

I send the training code to your email.

**Comment by Xiejc97** [comment]
@JoeHEZHAO 
Hi, thanks for your good work.
Can you release the training code in the github?
Thanks very much!

**Comment by JoeHEZHAO** [comment]
@Xiejc97 Please find file train_sdd.py in the repo.
