### ISSUE TITLE
Checkpoint/args for zara2&univ

### ISSUE THREAD

**Issue by Jlongli** [JoeHEZHAO/expert_traj#4]
Hi,
I can't find the corresponding files for zara2&univ in '_/checkpoint_ethucy_'. Would you please provide it for better reproductivity?

Thanks

**Comment by JoeHEZHAO** [comment]
Hi Jlong

Sorry for the delay. As we have talked in emails, now I have free time to get back to you.

I just update the model weights and expert-goal examples for these two subsets. Can you give it a try on Zara2 & Univ? I reproduce the results for these two subsets using the k-mean retrieval fashion.

Note that with the k-mean fashion, I find the results for **Zara2** now is ~0.9/0.26, which is different from 0.12/0.24 in the paper.. I use the 20 centroids for k-mean on top of DTW (100 smallest results) this time, whereas the original paper just use plain DTW.  Looks like it hurts the FDE but benefits the ADE a bit.

For the **Univ** subset, I find the updated result ok.

Thank you again for your interest. Please let me know if any problem.

**Comment by Jlongli** [comment]
Thanks a lot! 
With these, I can reproduce similar results now.
